spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/luck?serverTimezone=GMT%2B8&useUnicode=true&&characterEncoding=UTF-8
    username: root
    password: spwang
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
